[package]
name = "rustish-gb"
version = "0.1.0"
edition = "2021"

[features]
default = ["logging-file", "logging-stdout", "ly-stub"]
logging = []
logging-file = ["logging"]
logging-stdout = ["logging"]
ly-stub = []

[profile.release]
opt-level = 3
codegen-units = 1
debug = 0
strip = true
lto = true

[dependencies]
paste = "1.0"
clap = { version = "3.1", features = ["derive"] }
egui = "0.17"
egui_wgpu_backend = "0.17"
egui-winit = { version = "0.17", default_features = false, features = [] }
winit = "0.26"
winit_input_helper = "0.11"
pixels = "0.9"

#[dev-dependencies]
#bencher = "0.1.5"
#[[bench]]
#name = "bench"
#harness = false
