[package]
name = "rustish-gb"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
codegen-units = 1
debug = 0
strip = true
lto = true

[dependencies]
paste = "1.0"
clap = { version = "3.1", features = ["derive"] }
egui = { version = "0.17", optional = true }
egui_wgpu_backend = { version = "0.17", optional = true }
egui-winit = { version = "0.17", default_features = false, optional = true }
winit = { version = "0.26", optional = true }
winit_input_helper = { version = "0.11", optional = true }
pixels = { version = "0.9", optional = true }

[features]
default = ["gui", "logging-file", "ly-stub"]
# FEATURES
gui = ["egui", "egui_wgpu_backend", "egui-winit", "winit", "winit_input_helper", "pixels"]
# DEBUG FEAUTURES
ly-stub = []
logging = []
logging-file = ["logging"]
logging-stdout = ["logging"]
logging-all = ["logging-file", "logging-stdout"]


#[dev-dependencies]
#bencher = "0.1.5"
#[[bench]]
#name = "bench"
#harness = false
