[package]
name = "rustish-gb"
authors = ["griffi-gh <prasol258@gmail.com>"]
version = "0.0.0"
publish = false
edition = "2021"

[profile.release]
opt-level = 3
codegen-units = 1
debug = 0
strip = true
lto = true

[dependencies]
paste = "1.0"
clap = { version = "3.1", features = ["derive"] }
framework = { path = "lib/framework", optional = true }

[features]
default = ["gui", "ly-stub"]
# FEATURES
gui = ["framework"]
# DEBUG FEAUTURES
ly-stub = []
logging = []
logging-file = ["logging"]
logging-stdout = ["logging"]
logging-all = ["logging-file", "logging-stdout"]

#[dev-dependencies]
#bencher = "0.1.5"
#[[bench]]
#name = "bench"
#harness = false
