[package]
name = "rustish"
version = "0.1.0"
edition = "2021"


[profile.release-final]
inherits = "release"
opt-level = 3
codegen-units = 1
debug = 0
strip = true
lto = true

[dependencies]
paste = "^1.0"

#[dev-dependencies]
#bencher = "0.1.5"
#[[bench]]
#name = "bench"
#harness = false