[workspace]
members = [
  "yarge-core",
  "yarge-frontend-desktop",
  "yarge-frontend-nano"
]
resolver = "2"

[profile.dev.package."*"]
opt-level = 3

[profile.production]
inherits = "release"
strip = true
codegen-units = 1
lto = true
panic = "abort"
