[workspace]
members = [
  "yarge-core",
  "yarge-frontend-desktop"
]
resolver = "2"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
strip = true
codegen-units = 1
lto = true
panic = "abort"
