[package]
name = "rustish-gb"
version = "0.1.0"
edition = "2021"

[features]
default = ["logging-file", "logging-stdout", "ly-stub"]
logging = []
logging-file = ["logging"]
logging-stdout = ["logging"]
ly-stub = []

[profile.release]
opt-level = 3
codegen-units = 1
debug = 0
strip = true
lto = true

[dependencies]
paste = "^1.0"

#MAYBE use the bitfield library
#modular-bitfield = "0.11.2"

#[dev-dependencies]
#bencher = "0.1.5"
#[[bench]]
#name = "bench"
#harness = false
