name: Build

on:
  push:
    branches: [ master ]
    paths:
    - 'build.yml'
    - 'src/**'
    - '*.rs'
    - '*.toml'
    - '*.lock'
    - 'Cargo.*'
    - '!roms/**'
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Install required packages (Linux only)
      run: sudo apt update; sudo apt install libgtk-3-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev libatk1.0-dev gir1.2-gtk-3.0 
      if: runner.os == 'Linux'
    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        default: true
        override: true
    - uses: Swatinem/rust-cache@v1
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release
    - name: Upload build artifact (Linux only)
      uses: actions/upload-artifact@v3
      if: runner.os == 'Linux'
      with:
        name: release-lin64
        path: ./target/release/yarge-gb
    - name: Upload build artifact (Windows only)
      uses: actions/upload-artifact@v3
      if: runner.os == 'Windows'
      with:
        name: release-win64
        path: ./target/release/yarge-gb.exe
